#!/usr/bin/env bash
set -euo pipefail

# UltraBridge CalDAV — Interactive installer
# Safe to re-run: overwrites generated config files each time.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_SUPERNOTE_DIR="/mnt/supernote"
DEFAULT_PORT="8443"
DEFAULT_USERNAME="admin"

# --- helpers ---

info()  { printf '\033[1;34m==> %s\033[0m\n' "$*"; }
ok()    { printf '\033[1;32m OK \033[0m %s\n' "$*"; }
warn()  { printf '\033[1;33m WARN \033[0m %s\n' "$*"; }
fail()  { printf '\033[1;31m FAIL \033[0m %s\n' "$*"; exit 1; }

prompt() {
    local var="$1" msg="$2" default="$3"
    local input
    if [[ -n "$default" ]]; then
        printf '%s [%s]: ' "$msg" "$default"
    else
        printf '%s: ' "$msg"
    fi
    read -r input
    eval "$var=\"${input:-$default}\""
}

prompt_password() {
    local var="$1" msg="$2"
    local pw1 pw2
    while true; do
        printf '%s: ' "$msg"
        read -rs pw1
        echo
        printf 'Confirm password: '
        read -rs pw2
        echo
        if [[ "$pw1" == "$pw2" ]]; then
            if [[ -z "$pw1" ]]; then
                warn "Password cannot be empty. Try again."
                continue
            fi
            eval "$var=\"$pw1\""
            return
        fi
        warn "Passwords don't match. Try again."
    done
}

# --- pre-flight checks ---

info "UltraBridge CalDAV Installer"
echo

# Docker
if ! command -v docker &>/dev/null; then
    fail "Docker is not installed. Install Docker first."
fi
ok "Docker found"

# Docker Compose
if ! docker compose version &>/dev/null; then
    fail "Docker Compose (v2) not found. Install docker-compose-plugin."
fi
ok "Docker Compose found"

# Supernote stack directory
prompt SUPERNOTE_DIR "Supernote Private Cloud directory" "$DEFAULT_SUPERNOTE_DIR"

if [[ ! -f "$SUPERNOTE_DIR/docker-compose.yml" ]]; then
    fail "No docker-compose.yml found in $SUPERNOTE_DIR. Is the Supernote Private Cloud installed?"
fi
ok "Supernote stack found at $SUPERNOTE_DIR"

# .dbenv
if [[ ! -f "$SUPERNOTE_DIR/.dbenv" ]]; then
    fail "No .dbenv found in $SUPERNOTE_DIR. The Supernote Private Cloud must be configured first."
fi
ok ".dbenv found"

# MariaDB running?
if docker ps --format '{{.Names}}' | grep -q mariadb; then
    ok "MariaDB container is running"
else
    warn "MariaDB container doesn't appear to be running."
    echo "  UltraBridge needs MariaDB. Start the Supernote stack first:"
    echo "  cd $SUPERNOTE_DIR && docker compose up -d"
    echo
    printf 'Continue anyway? [y/N]: '
    read -r yn
    [[ "$yn" =~ ^[Yy] ]] || exit 1
fi

echo

# --- configuration ---

info "Configuration"
echo
echo "  UltraBridge needs a username and password for CalDAV/web access."
echo "  Your password will be hashed with bcrypt — the plaintext is never stored."
echo

prompt UB_USERNAME "Username" "$DEFAULT_USERNAME"
prompt_password UB_PASSWORD "Password"
prompt UB_PORT "Port to expose on host" "$DEFAULT_PORT"
prompt UB_COLLECTION_NAME "CalDAV collection name" "Supernote Tasks"

echo

# --- build image first (needed for password hashing) ---

info "Building UltraBridge Docker image..."

docker build -t ultrabridge:dev "$SCRIPT_DIR" || fail "Docker build failed"

ok "Image built"

# --- generate bcrypt hash using the binary we just built ---

info "Generating password hash..."

UB_PASSWORD_HASH=$(docker run --rm ultrabridge:dev hash-password "$UB_PASSWORD") \
    || fail "Failed to generate bcrypt hash"

if [[ ! "$UB_PASSWORD_HASH" =~ ^\$2 ]]; then
    fail "Generated hash doesn't look like bcrypt: $UB_PASSWORD_HASH"
fi
ok "Password hashed"

# Docker Compose env_file interprets $ as variable substitution.
# Escape $ as $$ so the bcrypt hash survives.
UB_PASSWORD_HASH_ESCAPED="${UB_PASSWORD_HASH//\$/\$\$}"

# --- write .ultrabridge.env ---

info "Writing $SUPERNOTE_DIR/.ultrabridge.env"

cat > "$SUPERNOTE_DIR/.ultrabridge.env" <<EOF
# UltraBridge Configuration (generated by install.sh)
# Re-run install.sh to change these settings.

# Auth
UB_USERNAME=$UB_USERNAME
UB_PASSWORD_HASH=$UB_PASSWORD_HASH_ESCAPED

# CalDAV
UB_CALDAV_COLLECTION_NAME=$UB_COLLECTION_NAME
UB_DUE_TIME_MODE=preserve

# Server
UB_LISTEN_ADDR=:8443
UB_WEB_ENABLED=true

# Logging
UB_LOG_LEVEL=info
UB_LOG_FORMAT=json
EOF

chmod 600 "$SUPERNOTE_DIR/.ultrabridge.env"
ok "Environment file written (permissions: 600)"

# --- write docker-compose.override.yml ---

info "Writing $SUPERNOTE_DIR/docker-compose.override.yml"

# Check if an override already exists with non-ultrabridge services
if [[ -f "$SUPERNOTE_DIR/docker-compose.override.yml" ]]; then
    if grep -q 'services:' "$SUPERNOTE_DIR/docker-compose.override.yml" && \
       grep -v -E '^\s*#|^\s*$|ultrabridge|services:|build:|context:|dockerfile:|container_name:|ports:|env_file:|volumes:|depends_on:|restart:' \
       "$SUPERNOTE_DIR/docker-compose.override.yml" | grep -q '[a-z]'; then
        warn "Existing docker-compose.override.yml contains other services."
        echo "  Backing up to docker-compose.override.yml.bak"
        cp "$SUPERNOTE_DIR/docker-compose.override.yml" "$SUPERNOTE_DIR/docker-compose.override.yml.bak"
    fi
fi

cat > "$SUPERNOTE_DIR/docker-compose.override.yml" <<EOF
services:
  ultrabridge:
    image: ultrabridge:dev
    build:
      context: $SCRIPT_DIR
      dockerfile: Dockerfile
    container_name: ultrabridge
    ports:
      - "${UB_PORT}:8443"
    env_file:
      - .ultrabridge.env
      - .dbenv
    depends_on:
      - mariadb
    restart: unless-stopped
EOF

ok "Docker Compose override written"

# --- build and start ---

# The Supernote stack's .dbenv is root-owned (600), so docker compose
# needs sudo to read it via env_file. This matches how the Supernote
# stack itself is managed.
COMPOSE="sudo docker compose -f $SUPERNOTE_DIR/docker-compose.yml -f $SUPERNOTE_DIR/docker-compose.override.yml"

echo
info "Starting UltraBridge (sudo required to read .dbenv)..."

$COMPOSE up -d --force-recreate ultrabridge || fail "Failed to start container"

# --- verify ---

info "Verifying..."
sleep 2

HEALTH_URL="http://localhost:${UB_PORT}/health"
if curl -sf "$HEALTH_URL" >/dev/null 2>&1; then
    ok "Health check passed: $HEALTH_URL"
else
    # Give it a few more seconds (DB connection can take a moment)
    sleep 3
    if curl -sf "$HEALTH_URL" >/dev/null 2>&1; then
        ok "Health check passed: $HEALTH_URL"
    else
        warn "Health check failed. Check logs:"
        echo "  $COMPOSE logs ultrabridge"
        echo
        echo "  Common causes:"
        echo "  - MariaDB not running"
        echo "  - No user in u_user table (open Supernote web UI first)"
        exit 1
    fi
fi

# --- done ---

echo
info "UltraBridge is running!"
echo
echo "  Web UI:          http://localhost:${UB_PORT}/"
echo "  CalDAV endpoint: http://localhost:${UB_PORT}/caldav/tasks/"
echo "  CalDAV discovery: http://localhost:${UB_PORT}/.well-known/caldav"
echo "  Health check:    http://localhost:${UB_PORT}/health"
echo
echo "  Username: $UB_USERNAME"
echo "  Password: (the one you just entered)"
echo
echo "  CalDAV client setup:"
echo "    Server URL: https://your-host/.well-known/caldav"
echo "    (Use a reverse proxy like NPM for HTTPS)"
echo
echo "  To reconfigure, just run this script again."
echo "  To view logs: docker logs -f ultrabridge"
echo
