package supernote

// pattern: Imperative Shell

import (
	"context"
	"fmt"
	"log/slog"

	"github.com/sysop/ultrabridge/internal/tasksync"
)

// SyncNotifier triggers device sync. Matches caldav.SyncNotifier.
type SyncNotifier interface {
	Notify(ctx context.Context) error
}

// Adapter implements tasksync.DeviceAdapter for Supernote devices via SPC REST API.
type Adapter struct {
	client   *Client
	notifier SyncNotifier
	logger   *slog.Logger
}

// NewAdapter creates a Supernote sync adapter.
func NewAdapter(apiURL, account, password string, notifier SyncNotifier, logger *slog.Logger) *Adapter {
	return &Adapter{
		client:   NewClient(apiURL, account, password, logger),
		notifier: notifier,
		logger:   logger,
	}
}

func (a *Adapter) ID() string { return "supernote" }

func (a *Adapter) Start(ctx context.Context) error {
	return a.client.Login(ctx)
}

func (a *Adapter) Stop() error { return nil }

func (a *Adapter) Pull(ctx context.Context, since string) ([]tasksync.RemoteTask, string, error) {
	spcTasks, err := a.client.FetchTasks(ctx)
	if err != nil {
		return nil, since, fmt.Errorf("fetch SPC tasks: %w", err)
	}

	a.logger.Info("pull fetched tasks from SPC", "count", len(spcTasks))
	var remote []tasksync.RemoteTask
	for _, spc := range spcTasks {
		a.logger.Debug("pull task", "id", spc.ID, "title", spc.Title, "deleted", spc.IsDeleted)
		if spc.IsDeleted == "Y" {
			continue
		}
		remote = append(remote, SPCTaskToRemote(spc))
	}

	// SPC doesn't support sync tokens — return empty token.
	// Change detection is done via ETag comparison in the sync engine.
	return remote, "", nil
}

func (a *Adapter) Push(ctx context.Context, changes []tasksync.Change) ([]tasksync.PushResult, error) {
	var updateBatch []SPCTask
	var results []tasksync.PushResult

	for _, c := range changes {
		switch c.Type {
		case tasksync.ChangeCreate:
			spc := RemoteToSPCTask(c.Remote, "")
			if err := a.client.CreateTask(ctx, spc); err != nil {
				a.logger.Warn("push create failed", "task_id", c.TaskID, "error", err)
				continue
			}
			results = append(results, tasksync.PushResult{
				TaskID:   c.TaskID,
				RemoteID: spc.ID, // Server-assigned (generated by RemoteToSPCTask)
			})

		case tasksync.ChangeUpdate:
			spc := RemoteToSPCTask(c.Remote, c.RemoteID)
			updateBatch = append(updateBatch, spc)
			results = append(results, tasksync.PushResult{
				TaskID:   c.TaskID,
				RemoteID: c.RemoteID,
			})

		case tasksync.ChangeDelete:
			if err := a.client.DeleteTask(ctx, c.RemoteID); err != nil {
				a.logger.Warn("push delete failed", "task_id", c.TaskID, "error", err)
			}
		}
	}

	// Bulk update
	if len(updateBatch) > 0 {
		if err := a.client.UpdateTasks(ctx, updateBatch); err != nil {
			return results, fmt.Errorf("bulk update: %w", err)
		}
	}

	// Trigger STARTSYNC so device picks up changes
	if a.notifier != nil {
		if err := a.notifier.Notify(ctx); err != nil {
			a.logger.Warn("STARTSYNC notification failed", "error", err)
		}
	}

	return results, nil
}
