// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: boox.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NoteInfo — parsed from {noteId}/note/pb/note_info within the ZIP.
// Source: NoteInfoProto.java (NoteInfo inner class)
type NoteInfo struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	UniqueId  string                 `protobuf:"bytes,1,opt,name=uniqueId,proto3" json:"uniqueId,omitempty"`
	CreatedAt int64                  `protobuf:"varint,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// Field 3 not observed in decompiled code
	ParentUniqueId       string  `protobuf:"bytes,4,opt,name=parentUniqueId,proto3" json:"parentUniqueId,omitempty"`
	SubPageName          string  `protobuf:"bytes,5,opt,name=subPageName,proto3" json:"subPageName,omitempty"`
	Title                string  `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	ExtraAttributes      string  `protobuf:"bytes,7,opt,name=extraAttributes,proto3" json:"extraAttributes,omitempty"`
	Type                 int32   `protobuf:"varint,8,opt,name=type,proto3" json:"type,omitempty"`
	StrokeWidth          float32 `protobuf:"fixed32,9,opt,name=strokeWidth,proto3" json:"strokeWidth,omitempty"`
	EraserWidth          float32 `protobuf:"fixed32,10,opt,name=eraserWidth,proto3" json:"eraserWidth,omitempty"`
	NotePenInfo          string  `protobuf:"bytes,11,opt,name=notePenInfo,proto3" json:"notePenInfo,omitempty"`
	NotePageInfo         string  `protobuf:"bytes,12,opt,name=notePageInfo,proto3" json:"notePageInfo,omitempty"`
	NoteBackground       string  `protobuf:"bytes,13,opt,name=noteBackground,proto3" json:"noteBackground,omitempty"`
	DeviceInfo           string  `protobuf:"bytes,14,opt,name=deviceInfo,proto3" json:"deviceInfo,omitempty"`
	StrokeColor          int32   `protobuf:"varint,15,opt,name=strokeColor,proto3" json:"strokeColor,omitempty"`
	CurrentShapeType     int32   `protobuf:"varint,16,opt,name=currentShapeType,proto3" json:"currentShapeType,omitempty"`
	Background           string  `protobuf:"bytes,17,opt,name=background,proto3" json:"background,omitempty"`
	LineLayoutBackground string  `protobuf:"bytes,18,opt,name=lineLayoutBackground,proto3" json:"lineLayoutBackground,omitempty"`
	Position             int32   `protobuf:"varint,19,opt,name=position,proto3" json:"position,omitempty"`
	PageNameList         string  `protobuf:"bytes,20,opt,name=pageNameList,proto3" json:"pageNameList,omitempty"` // JSON array of page ID strings
	RichTextPageNameList string  `protobuf:"bytes,21,opt,name=richTextPageNameList,proto3" json:"richTextPageNameList,omitempty"`
	PageOriginWidth      float32 `protobuf:"fixed32,22,opt,name=pageOriginWidth,proto3" json:"pageOriginWidth,omitempty"`
	PageOriginHeight     float32 `protobuf:"fixed32,23,opt,name=pageOriginHeight,proto3" json:"pageOriginHeight,omitempty"`
	Source               string  `protobuf:"bytes,24,opt,name=source,proto3" json:"source,omitempty"`
	AssociateDate        string  `protobuf:"bytes,25,opt,name=associateDate,proto3" json:"associateDate,omitempty"`
	AsyncStatus          int32   `protobuf:"varint,26,opt,name=asyncStatus,proto3" json:"asyncStatus,omitempty"`
	EncryptionType       int32   `protobuf:"varint,27,opt,name=encryptionType,proto3" json:"encryptionType,omitempty"`
	Digest               string  `protobuf:"bytes,28,opt,name=digest,proto3" json:"digest,omitempty"`
	AssociationId        string  `protobuf:"bytes,29,opt,name=associationId,proto3" json:"associationId,omitempty"`
	AssociationType      int32   `protobuf:"varint,30,opt,name=associationType,proto3" json:"associationType,omitempty"`
	Status               int32   `protobuf:"varint,31,opt,name=status,proto3" json:"status,omitempty"`
	CloudNoteSize        int64   `protobuf:"varint,32,opt,name=cloudNoteSize,proto3" json:"cloudNoteSize,omitempty"`
	CloudUpdatedAt       int64   `protobuf:"varint,33,opt,name=cloudUpdatedAt,proto3" json:"cloudUpdatedAt,omitempty"`
	CommitId             string  `protobuf:"bytes,34,opt,name=commitId,proto3" json:"commitId,omitempty"`
	EmbeddedAt           int64   `protobuf:"varint,35,opt,name=embeddedAt,proto3" json:"embeddedAt,omitempty"`
	SyncFrom             string  `protobuf:"bytes,36,opt,name=syncFrom,proto3" json:"syncFrom,omitempty"`
	NoteSyncStatus       int32   `protobuf:"varint,37,opt,name=noteSyncStatus,proto3" json:"noteSyncStatus,omitempty"`
	Favorite             bool    `protobuf:"varint,38,opt,name=favorite,proto3" json:"favorite,omitempty"`
	// Fields 39-40 not observed
	GroupId             string `protobuf:"bytes,41,opt,name=groupId,proto3" json:"groupId,omitempty"`
	ThumbnailRes        string `protobuf:"bytes,42,opt,name=thumbnailRes,proto3" json:"thumbnailRes,omitempty"`
	ActiveScene         string `protobuf:"bytes,43,opt,name=activeScene,proto3" json:"activeScene,omitempty"`
	RemovePageList      string `protobuf:"bytes,44,opt,name=removePageList,proto3" json:"removePageList,omitempty"`
	MiniRequiredVersion int32  `protobuf:"varint,45,opt,name=miniRequiredVersion,proto3" json:"miniRequiredVersion,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NoteInfo) Reset() {
	*x = NoteInfo{}
	mi := &file_boox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteInfo) ProtoMessage() {}

func (x *NoteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_boox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteInfo.ProtoReflect.Descriptor instead.
func (*NoteInfo) Descriptor() ([]byte, []int) {
	return file_boox_proto_rawDescGZIP(), []int{0}
}

func (x *NoteInfo) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

func (x *NoteInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *NoteInfo) GetParentUniqueId() string {
	if x != nil {
		return x.ParentUniqueId
	}
	return ""
}

func (x *NoteInfo) GetSubPageName() string {
	if x != nil {
		return x.SubPageName
	}
	return ""
}

func (x *NoteInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoteInfo) GetExtraAttributes() string {
	if x != nil {
		return x.ExtraAttributes
	}
	return ""
}

func (x *NoteInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *NoteInfo) GetStrokeWidth() float32 {
	if x != nil {
		return x.StrokeWidth
	}
	return 0
}

func (x *NoteInfo) GetEraserWidth() float32 {
	if x != nil {
		return x.EraserWidth
	}
	return 0
}

func (x *NoteInfo) GetNotePenInfo() string {
	if x != nil {
		return x.NotePenInfo
	}
	return ""
}

func (x *NoteInfo) GetNotePageInfo() string {
	if x != nil {
		return x.NotePageInfo
	}
	return ""
}

func (x *NoteInfo) GetNoteBackground() string {
	if x != nil {
		return x.NoteBackground
	}
	return ""
}

func (x *NoteInfo) GetDeviceInfo() string {
	if x != nil {
		return x.DeviceInfo
	}
	return ""
}

func (x *NoteInfo) GetStrokeColor() int32 {
	if x != nil {
		return x.StrokeColor
	}
	return 0
}

func (x *NoteInfo) GetCurrentShapeType() int32 {
	if x != nil {
		return x.CurrentShapeType
	}
	return 0
}

func (x *NoteInfo) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

func (x *NoteInfo) GetLineLayoutBackground() string {
	if x != nil {
		return x.LineLayoutBackground
	}
	return ""
}

func (x *NoteInfo) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *NoteInfo) GetPageNameList() string {
	if x != nil {
		return x.PageNameList
	}
	return ""
}

func (x *NoteInfo) GetRichTextPageNameList() string {
	if x != nil {
		return x.RichTextPageNameList
	}
	return ""
}

func (x *NoteInfo) GetPageOriginWidth() float32 {
	if x != nil {
		return x.PageOriginWidth
	}
	return 0
}

func (x *NoteInfo) GetPageOriginHeight() float32 {
	if x != nil {
		return x.PageOriginHeight
	}
	return 0
}

func (x *NoteInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *NoteInfo) GetAssociateDate() string {
	if x != nil {
		return x.AssociateDate
	}
	return ""
}

func (x *NoteInfo) GetAsyncStatus() int32 {
	if x != nil {
		return x.AsyncStatus
	}
	return 0
}

func (x *NoteInfo) GetEncryptionType() int32 {
	if x != nil {
		return x.EncryptionType
	}
	return 0
}

func (x *NoteInfo) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *NoteInfo) GetAssociationId() string {
	if x != nil {
		return x.AssociationId
	}
	return ""
}

func (x *NoteInfo) GetAssociationType() int32 {
	if x != nil {
		return x.AssociationType
	}
	return 0
}

func (x *NoteInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *NoteInfo) GetCloudNoteSize() int64 {
	if x != nil {
		return x.CloudNoteSize
	}
	return 0
}

func (x *NoteInfo) GetCloudUpdatedAt() int64 {
	if x != nil {
		return x.CloudUpdatedAt
	}
	return 0
}

func (x *NoteInfo) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *NoteInfo) GetEmbeddedAt() int64 {
	if x != nil {
		return x.EmbeddedAt
	}
	return 0
}

func (x *NoteInfo) GetSyncFrom() string {
	if x != nil {
		return x.SyncFrom
	}
	return ""
}

func (x *NoteInfo) GetNoteSyncStatus() int32 {
	if x != nil {
		return x.NoteSyncStatus
	}
	return 0
}

func (x *NoteInfo) GetFavorite() bool {
	if x != nil {
		return x.Favorite
	}
	return false
}

func (x *NoteInfo) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *NoteInfo) GetThumbnailRes() string {
	if x != nil {
		return x.ThumbnailRes
	}
	return ""
}

func (x *NoteInfo) GetActiveScene() string {
	if x != nil {
		return x.ActiveScene
	}
	return ""
}

func (x *NoteInfo) GetRemovePageList() string {
	if x != nil {
		return x.RemovePageList
	}
	return ""
}

func (x *NoteInfo) GetMiniRequiredVersion() int32 {
	if x != nil {
		return x.MiniRequiredVersion
	}
	return 0
}

// VirtualDoc — parsed from {noteId}/virtual/doc/pb/{docId}.
// Source: VirtualDocPageProto.java (VirtualDoc inner class)
type VirtualDoc struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UniqueId        string                 `protobuf:"bytes,1,opt,name=uniqueId,proto3" json:"uniqueId,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	ViewportId      string                 `protobuf:"bytes,4,opt,name=viewportId,proto3" json:"viewportId,omitempty"`
	ActualScale     float32                `protobuf:"fixed32,5,opt,name=actualScale,proto3" json:"actualScale,omitempty"`
	OffsetX         float32                `protobuf:"fixed32,6,opt,name=offsetX,proto3" json:"offsetX,omitempty"`
	OffsetY         float32                `protobuf:"fixed32,7,opt,name=offsetY,proto3" json:"offsetY,omitempty"`
	CoverPageId     string                 `protobuf:"bytes,8,opt,name=coverPageId,proto3" json:"coverPageId,omitempty"`
	DefaultTemplate string                 `protobuf:"bytes,9,opt,name=defaultTemplate,proto3" json:"defaultTemplate,omitempty"`
	DocOptions      string                 `protobuf:"bytes,10,opt,name=docOptions,proto3" json:"docOptions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VirtualDoc) Reset() {
	*x = VirtualDoc{}
	mi := &file_boox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualDoc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualDoc) ProtoMessage() {}

func (x *VirtualDoc) ProtoReflect() protoreflect.Message {
	mi := &file_boox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualDoc.ProtoReflect.Descriptor instead.
func (*VirtualDoc) Descriptor() ([]byte, []int) {
	return file_boox_proto_rawDescGZIP(), []int{1}
}

func (x *VirtualDoc) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

func (x *VirtualDoc) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *VirtualDoc) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *VirtualDoc) GetViewportId() string {
	if x != nil {
		return x.ViewportId
	}
	return ""
}

func (x *VirtualDoc) GetActualScale() float32 {
	if x != nil {
		return x.ActualScale
	}
	return 0
}

func (x *VirtualDoc) GetOffsetX() float32 {
	if x != nil {
		return x.OffsetX
	}
	return 0
}

func (x *VirtualDoc) GetOffsetY() float32 {
	if x != nil {
		return x.OffsetY
	}
	return 0
}

func (x *VirtualDoc) GetCoverPageId() string {
	if x != nil {
		return x.CoverPageId
	}
	return ""
}

func (x *VirtualDoc) GetDefaultTemplate() string {
	if x != nil {
		return x.DefaultTemplate
	}
	return ""
}

func (x *VirtualDoc) GetDocOptions() string {
	if x != nil {
		return x.DocOptions
	}
	return ""
}

// VirtualPage — parsed from {noteId}/virtual/page/pb/{pageId}.
// Source: VirtualDocPageProto.java (VirtualPage inner class)
type VirtualPage struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PageId              string                 `protobuf:"bytes,1,opt,name=pageId,proto3" json:"pageId,omitempty"`
	CreatedAt           int64                  `protobuf:"varint,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt           int64                  `protobuf:"varint,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	OrderIndex          float32                `protobuf:"fixed32,4,opt,name=orderIndex,proto3" json:"orderIndex,omitempty"`
	Status              int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	PageSize            string                 `protobuf:"bytes,6,opt,name=pageSize,proto3" json:"pageSize,omitempty"` // JSON: e.g. "1860.0x2480.0" or "{\"width\":1860,\"height\":2480}"
	PageSizeWithMargin  string                 `protobuf:"bytes,7,opt,name=pageSizeWithMargin,proto3" json:"pageSizeWithMargin,omitempty"`
	ContentPageSize     string                 `protobuf:"bytes,8,opt,name=contentPageSize,proto3" json:"contentPageSize,omitempty"`
	ContentType         string                 `protobuf:"bytes,9,opt,name=contentType,proto3" json:"contentType,omitempty"`
	ContentRelativePath string                 `protobuf:"bytes,10,opt,name=contentRelativePath,proto3" json:"contentRelativePath,omitempty"`
	ContentPageId       string                 `protobuf:"bytes,11,opt,name=contentPageId,proto3" json:"contentPageId,omitempty"`
	ContentId           string                 `protobuf:"bytes,12,opt,name=contentId,proto3" json:"contentId,omitempty"`
	ContentStatus       int32                  `protobuf:"varint,13,opt,name=contentStatus,proto3" json:"contentStatus,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *VirtualPage) Reset() {
	*x = VirtualPage{}
	mi := &file_boox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualPage) ProtoMessage() {}

func (x *VirtualPage) ProtoReflect() protoreflect.Message {
	mi := &file_boox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualPage.ProtoReflect.Descriptor instead.
func (*VirtualPage) Descriptor() ([]byte, []int) {
	return file_boox_proto_rawDescGZIP(), []int{2}
}

func (x *VirtualPage) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *VirtualPage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *VirtualPage) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *VirtualPage) GetOrderIndex() float32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

func (x *VirtualPage) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *VirtualPage) GetPageSize() string {
	if x != nil {
		return x.PageSize
	}
	return ""
}

func (x *VirtualPage) GetPageSizeWithMargin() string {
	if x != nil {
		return x.PageSizeWithMargin
	}
	return ""
}

func (x *VirtualPage) GetContentPageSize() string {
	if x != nil {
		return x.ContentPageSize
	}
	return ""
}

func (x *VirtualPage) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *VirtualPage) GetContentRelativePath() string {
	if x != nil {
		return x.ContentRelativePath
	}
	return ""
}

func (x *VirtualPage) GetContentPageId() string {
	if x != nil {
		return x.ContentPageId
	}
	return ""
}

func (x *VirtualPage) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *VirtualPage) GetContentStatus() int32 {
	if x != nil {
		return x.ContentStatus
	}
	return 0
}

// VirtualPageList — wrapper for repeated VirtualPage.
// Source: VirtualDocPageProto.java (VirtualPageList inner class)
type VirtualPageList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proto         []*VirtualPage         `protobuf:"bytes,1,rep,name=proto,proto3" json:"proto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualPageList) Reset() {
	*x = VirtualPageList{}
	mi := &file_boox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualPageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualPageList) ProtoMessage() {}

func (x *VirtualPageList) ProtoReflect() protoreflect.Message {
	mi := &file_boox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualPageList.ProtoReflect.Descriptor instead.
func (*VirtualPageList) Descriptor() ([]byte, []int) {
	return file_boox_proto_rawDescGZIP(), []int{3}
}

func (x *VirtualPageList) GetProto() []*VirtualPage {
	if x != nil {
		return x.Proto
	}
	return nil
}

// NotePageModel — parsed from {noteId}/pageModel/pb/{pageModelId}.
// Source: NotePageModelProto.java
type NotePageModel struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UniqueId       string                 `protobuf:"bytes,1,opt,name=uniqueId,proto3" json:"uniqueId,omitempty"`
	LayerList      string                 `protobuf:"bytes,2,opt,name=layerList,proto3" json:"layerList,omitempty"` // JSON array
	CurrentLayerId string                 `protobuf:"bytes,3,opt,name=currentLayerId,proto3" json:"currentLayerId,omitempty"`
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	PageSize       string                 `protobuf:"bytes,7,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotePageModel) Reset() {
	*x = NotePageModel{}
	mi := &file_boox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotePageModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotePageModel) ProtoMessage() {}

func (x *NotePageModel) ProtoReflect() protoreflect.Message {
	mi := &file_boox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotePageModel.ProtoReflect.Descriptor instead.
func (*NotePageModel) Descriptor() ([]byte, []int) {
	return file_boox_proto_rawDescGZIP(), []int{4}
}

func (x *NotePageModel) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

func (x *NotePageModel) GetLayerList() string {
	if x != nil {
		return x.LayerList
	}
	return ""
}

func (x *NotePageModel) GetCurrentLayerId() string {
	if x != nil {
		return x.CurrentLayerId
	}
	return ""
}

func (x *NotePageModel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotePageModel) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *NotePageModel) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *NotePageModel) GetPageSize() string {
	if x != nil {
		return x.PageSize
	}
	return ""
}

// NotePageModelList — wrapper for repeated NotePageModel.
type NotePageModelList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proto         []*NotePageModel       `protobuf:"bytes,1,rep,name=proto,proto3" json:"proto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotePageModelList) Reset() {
	*x = NotePageModelList{}
	mi := &file_boox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotePageModelList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotePageModelList) ProtoMessage() {}

func (x *NotePageModelList) ProtoReflect() protoreflect.Message {
	mi := &file_boox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotePageModelList.ProtoReflect.Descriptor instead.
func (*NotePageModelList) Descriptor() ([]byte, []int) {
	return file_boox_proto_rawDescGZIP(), []int{5}
}

func (x *NotePageModelList) GetProto() []*NotePageModel {
	if x != nil {
		return x.Proto
	}
	return nil
}

// ShapeInfoProto — stroke/shape metadata.
// Source: NoteShapeDocProto.java, BOOX_STROKE_FORMAT.md
type ShapeInfoProto struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UniqueId       string                 `protobuf:"bytes,1,opt,name=uniqueId,proto3" json:"uniqueId,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Color          int32                  `protobuf:"varint,4,opt,name=color,proto3" json:"color,omitempty"` // ARGB packed int
	Thickness      float32                `protobuf:"fixed32,5,opt,name=thickness,proto3" json:"thickness,omitempty"`
	Zorder         int32                  `protobuf:"varint,6,opt,name=zorder,proto3" json:"zorder,omitempty"`
	BoundingRect   string                 `protobuf:"bytes,7,opt,name=boundingRect,proto3" json:"boundingRect,omitempty"` // JSON: {"left":f,"top":f,"right":f,"bottom":f}
	MatrixValues   string                 `protobuf:"bytes,8,opt,name=matrixValues,proto3" json:"matrixValues,omitempty"` // JSON: affine transform matrix values
	TextStyle      string                 `protobuf:"bytes,9,opt,name=textStyle,proto3" json:"textStyle,omitempty"`
	Text           string                 `protobuf:"bytes,10,opt,name=text,proto3" json:"text,omitempty"`
	CreateArgs     string                 `protobuf:"bytes,11,opt,name=createArgs,proto3" json:"createArgs,omitempty"`
	ShapeType      int32                  `protobuf:"varint,12,opt,name=shapeType,proto3" json:"shapeType,omitempty"` // see ShapeType constants
	GroupId        string                 `protobuf:"bytes,13,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Resource       string                 `protobuf:"bytes,14,opt,name=resource,proto3" json:"resource,omitempty"`
	ShapeStatus    int32                  `protobuf:"varint,15,opt,name=shapeStatus,proto3" json:"shapeStatus,omitempty"`
	RevisionId     string                 `protobuf:"bytes,16,opt,name=revisionId,proto3" json:"revisionId,omitempty"`
	LineStyle      string                 `protobuf:"bytes,17,opt,name=lineStyle,proto3" json:"lineStyle,omitempty"`
	InfoRevisionId string                 `protobuf:"bytes,18,opt,name=infoRevisionId,proto3" json:"infoRevisionId,omitempty"`
	TagIdList      string                 `protobuf:"bytes,19,opt,name=tagIdList,proto3" json:"tagIdList,omitempty"`
	Extra          string                 `protobuf:"bytes,20,opt,name=extra,proto3" json:"extra,omitempty"`
	LinkIdList     string                 `protobuf:"bytes,21,opt,name=linkIdList,proto3" json:"linkIdList,omitempty"`
	RichText       string                 `protobuf:"bytes,22,opt,name=richText,proto3" json:"richText,omitempty"`
	FillColor      int32                  `protobuf:"varint,23,opt,name=fillColor,proto3" json:"fillColor,omitempty"` // ARGB packed int
	PointList      []byte                 `protobuf:"bytes,24,opt,name=pointList,proto3" json:"pointList,omitempty"`  // inline stroke data (often empty; see point files)
	ConnectionBean string                 `protobuf:"bytes,25,opt,name=connectionBean,proto3" json:"connectionBean,omitempty"`
	OptionsRepo    string                 `protobuf:"bytes,26,opt,name=optionsRepo,proto3" json:"optionsRepo,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShapeInfoProto) Reset() {
	*x = ShapeInfoProto{}
	mi := &file_boox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShapeInfoProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShapeInfoProto) ProtoMessage() {}

func (x *ShapeInfoProto) ProtoReflect() protoreflect.Message {
	mi := &file_boox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShapeInfoProto.ProtoReflect.Descriptor instead.
func (*ShapeInfoProto) Descriptor() ([]byte, []int) {
	return file_boox_proto_rawDescGZIP(), []int{6}
}

func (x *ShapeInfoProto) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

func (x *ShapeInfoProto) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ShapeInfoProto) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ShapeInfoProto) GetColor() int32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *ShapeInfoProto) GetThickness() float32 {
	if x != nil {
		return x.Thickness
	}
	return 0
}

func (x *ShapeInfoProto) GetZorder() int32 {
	if x != nil {
		return x.Zorder
	}
	return 0
}

func (x *ShapeInfoProto) GetBoundingRect() string {
	if x != nil {
		return x.BoundingRect
	}
	return ""
}

func (x *ShapeInfoProto) GetMatrixValues() string {
	if x != nil {
		return x.MatrixValues
	}
	return ""
}

func (x *ShapeInfoProto) GetTextStyle() string {
	if x != nil {
		return x.TextStyle
	}
	return ""
}

func (x *ShapeInfoProto) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ShapeInfoProto) GetCreateArgs() string {
	if x != nil {
		return x.CreateArgs
	}
	return ""
}

func (x *ShapeInfoProto) GetShapeType() int32 {
	if x != nil {
		return x.ShapeType
	}
	return 0
}

func (x *ShapeInfoProto) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ShapeInfoProto) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ShapeInfoProto) GetShapeStatus() int32 {
	if x != nil {
		return x.ShapeStatus
	}
	return 0
}

func (x *ShapeInfoProto) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *ShapeInfoProto) GetLineStyle() string {
	if x != nil {
		return x.LineStyle
	}
	return ""
}

func (x *ShapeInfoProto) GetInfoRevisionId() string {
	if x != nil {
		return x.InfoRevisionId
	}
	return ""
}

func (x *ShapeInfoProto) GetTagIdList() string {
	if x != nil {
		return x.TagIdList
	}
	return ""
}

func (x *ShapeInfoProto) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *ShapeInfoProto) GetLinkIdList() string {
	if x != nil {
		return x.LinkIdList
	}
	return ""
}

func (x *ShapeInfoProto) GetRichText() string {
	if x != nil {
		return x.RichText
	}
	return ""
}

func (x *ShapeInfoProto) GetFillColor() int32 {
	if x != nil {
		return x.FillColor
	}
	return 0
}

func (x *ShapeInfoProto) GetPointList() []byte {
	if x != nil {
		return x.PointList
	}
	return nil
}

func (x *ShapeInfoProto) GetConnectionBean() string {
	if x != nil {
		return x.ConnectionBean
	}
	return ""
}

func (x *ShapeInfoProto) GetOptionsRepo() string {
	if x != nil {
		return x.OptionsRepo
	}
	return ""
}

// ShapeInfoProtoList — wrapper for repeated ShapeInfoProto.
// Serialized inside nested ZIP at shape/{pageId}#...zip
type ShapeInfoProtoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proto         []*ShapeInfoProto      `protobuf:"bytes,1,rep,name=proto,proto3" json:"proto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShapeInfoProtoList) Reset() {
	*x = ShapeInfoProtoList{}
	mi := &file_boox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShapeInfoProtoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShapeInfoProtoList) ProtoMessage() {}

func (x *ShapeInfoProtoList) ProtoReflect() protoreflect.Message {
	mi := &file_boox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShapeInfoProtoList.ProtoReflect.Descriptor instead.
func (*ShapeInfoProtoList) Descriptor() ([]byte, []int) {
	return file_boox_proto_rawDescGZIP(), []int{7}
}

func (x *ShapeInfoProtoList) GetProto() []*ShapeInfoProto {
	if x != nil {
		return x.Proto
	}
	return nil
}

var File_boox_proto protoreflect.FileDescriptor

const file_boox_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"boox.proto\x12\x06booxpb\"\xcc\v\n" +
	"\bNoteInfo\x12\x1a\n" +
	"\buniqueId\x18\x01 \x01(\tR\buniqueId\x12\x1c\n" +
	"\tcreatedAt\x18\x02 \x01(\x03R\tcreatedAt\x12&\n" +
	"\x0eparentUniqueId\x18\x04 \x01(\tR\x0eparentUniqueId\x12 \n" +
	"\vsubPageName\x18\x05 \x01(\tR\vsubPageName\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12(\n" +
	"\x0fextraAttributes\x18\a \x01(\tR\x0fextraAttributes\x12\x12\n" +
	"\x04type\x18\b \x01(\x05R\x04type\x12 \n" +
	"\vstrokeWidth\x18\t \x01(\x02R\vstrokeWidth\x12 \n" +
	"\veraserWidth\x18\n" +
	" \x01(\x02R\veraserWidth\x12 \n" +
	"\vnotePenInfo\x18\v \x01(\tR\vnotePenInfo\x12\"\n" +
	"\fnotePageInfo\x18\f \x01(\tR\fnotePageInfo\x12&\n" +
	"\x0enoteBackground\x18\r \x01(\tR\x0enoteBackground\x12\x1e\n" +
	"\n" +
	"deviceInfo\x18\x0e \x01(\tR\n" +
	"deviceInfo\x12 \n" +
	"\vstrokeColor\x18\x0f \x01(\x05R\vstrokeColor\x12*\n" +
	"\x10currentShapeType\x18\x10 \x01(\x05R\x10currentShapeType\x12\x1e\n" +
	"\n" +
	"background\x18\x11 \x01(\tR\n" +
	"background\x122\n" +
	"\x14lineLayoutBackground\x18\x12 \x01(\tR\x14lineLayoutBackground\x12\x1a\n" +
	"\bposition\x18\x13 \x01(\x05R\bposition\x12\"\n" +
	"\fpageNameList\x18\x14 \x01(\tR\fpageNameList\x122\n" +
	"\x14richTextPageNameList\x18\x15 \x01(\tR\x14richTextPageNameList\x12(\n" +
	"\x0fpageOriginWidth\x18\x16 \x01(\x02R\x0fpageOriginWidth\x12*\n" +
	"\x10pageOriginHeight\x18\x17 \x01(\x02R\x10pageOriginHeight\x12\x16\n" +
	"\x06source\x18\x18 \x01(\tR\x06source\x12$\n" +
	"\rassociateDate\x18\x19 \x01(\tR\rassociateDate\x12 \n" +
	"\vasyncStatus\x18\x1a \x01(\x05R\vasyncStatus\x12&\n" +
	"\x0eencryptionType\x18\x1b \x01(\x05R\x0eencryptionType\x12\x16\n" +
	"\x06digest\x18\x1c \x01(\tR\x06digest\x12$\n" +
	"\rassociationId\x18\x1d \x01(\tR\rassociationId\x12(\n" +
	"\x0fassociationType\x18\x1e \x01(\x05R\x0fassociationType\x12\x16\n" +
	"\x06status\x18\x1f \x01(\x05R\x06status\x12$\n" +
	"\rcloudNoteSize\x18  \x01(\x03R\rcloudNoteSize\x12&\n" +
	"\x0ecloudUpdatedAt\x18! \x01(\x03R\x0ecloudUpdatedAt\x12\x1a\n" +
	"\bcommitId\x18\" \x01(\tR\bcommitId\x12\x1e\n" +
	"\n" +
	"embeddedAt\x18# \x01(\x03R\n" +
	"embeddedAt\x12\x1a\n" +
	"\bsyncFrom\x18$ \x01(\tR\bsyncFrom\x12&\n" +
	"\x0enoteSyncStatus\x18% \x01(\x05R\x0enoteSyncStatus\x12\x1a\n" +
	"\bfavorite\x18& \x01(\bR\bfavorite\x12\x18\n" +
	"\agroupId\x18) \x01(\tR\agroupId\x12\"\n" +
	"\fthumbnailRes\x18* \x01(\tR\fthumbnailRes\x12 \n" +
	"\vactiveScene\x18+ \x01(\tR\vactiveScene\x12&\n" +
	"\x0eremovePageList\x18, \x01(\tR\x0eremovePageList\x120\n" +
	"\x13miniRequiredVersion\x18- \x01(\x05R\x13miniRequiredVersion\"\xc6\x02\n" +
	"\n" +
	"VirtualDoc\x12\x1a\n" +
	"\buniqueId\x18\x01 \x01(\tR\buniqueId\x12\x1c\n" +
	"\tcreatedAt\x18\x02 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x03 \x01(\x03R\tupdatedAt\x12\x1e\n" +
	"\n" +
	"viewportId\x18\x04 \x01(\tR\n" +
	"viewportId\x12 \n" +
	"\vactualScale\x18\x05 \x01(\x02R\vactualScale\x12\x18\n" +
	"\aoffsetX\x18\x06 \x01(\x02R\aoffsetX\x12\x18\n" +
	"\aoffsetY\x18\a \x01(\x02R\aoffsetY\x12 \n" +
	"\vcoverPageId\x18\b \x01(\tR\vcoverPageId\x12(\n" +
	"\x0fdefaultTemplate\x18\t \x01(\tR\x0fdefaultTemplate\x12\x1e\n" +
	"\n" +
	"docOptions\x18\n" +
	" \x01(\tR\n" +
	"docOptions\"\xcd\x03\n" +
	"\vVirtualPage\x12\x16\n" +
	"\x06pageId\x18\x01 \x01(\tR\x06pageId\x12\x1c\n" +
	"\tcreatedAt\x18\x02 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x03 \x01(\x03R\tupdatedAt\x12\x1e\n" +
	"\n" +
	"orderIndex\x18\x04 \x01(\x02R\n" +
	"orderIndex\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1a\n" +
	"\bpageSize\x18\x06 \x01(\tR\bpageSize\x12.\n" +
	"\x12pageSizeWithMargin\x18\a \x01(\tR\x12pageSizeWithMargin\x12(\n" +
	"\x0fcontentPageSize\x18\b \x01(\tR\x0fcontentPageSize\x12 \n" +
	"\vcontentType\x18\t \x01(\tR\vcontentType\x120\n" +
	"\x13contentRelativePath\x18\n" +
	" \x01(\tR\x13contentRelativePath\x12$\n" +
	"\rcontentPageId\x18\v \x01(\tR\rcontentPageId\x12\x1c\n" +
	"\tcontentId\x18\f \x01(\tR\tcontentId\x12$\n" +
	"\rcontentStatus\x18\r \x01(\x05R\rcontentStatus\"<\n" +
	"\x0fVirtualPageList\x12)\n" +
	"\x05proto\x18\x01 \x03(\v2\x13.booxpb.VirtualPageR\x05proto\"\xdf\x01\n" +
	"\rNotePageModel\x12\x1a\n" +
	"\buniqueId\x18\x01 \x01(\tR\buniqueId\x12\x1c\n" +
	"\tlayerList\x18\x02 \x01(\tR\tlayerList\x12&\n" +
	"\x0ecurrentLayerId\x18\x03 \x01(\tR\x0ecurrentLayerId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x06 \x01(\x03R\tupdatedAt\x12\x1a\n" +
	"\bpageSize\x18\a \x01(\tR\bpageSize\"@\n" +
	"\x11NotePageModelList\x12+\n" +
	"\x05proto\x18\x01 \x03(\v2\x15.booxpb.NotePageModelR\x05proto\"\xa0\x06\n" +
	"\x0eShapeInfoProto\x12\x1a\n" +
	"\buniqueId\x18\x01 \x01(\tR\buniqueId\x12\x1c\n" +
	"\tcreatedAt\x18\x02 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x03 \x01(\x03R\tupdatedAt\x12\x14\n" +
	"\x05color\x18\x04 \x01(\x05R\x05color\x12\x1c\n" +
	"\tthickness\x18\x05 \x01(\x02R\tthickness\x12\x16\n" +
	"\x06zorder\x18\x06 \x01(\x05R\x06zorder\x12\"\n" +
	"\fboundingRect\x18\a \x01(\tR\fboundingRect\x12\"\n" +
	"\fmatrixValues\x18\b \x01(\tR\fmatrixValues\x12\x1c\n" +
	"\ttextStyle\x18\t \x01(\tR\ttextStyle\x12\x12\n" +
	"\x04text\x18\n" +
	" \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"createArgs\x18\v \x01(\tR\n" +
	"createArgs\x12\x1c\n" +
	"\tshapeType\x18\f \x01(\x05R\tshapeType\x12\x18\n" +
	"\agroupId\x18\r \x01(\tR\agroupId\x12\x1a\n" +
	"\bresource\x18\x0e \x01(\tR\bresource\x12 \n" +
	"\vshapeStatus\x18\x0f \x01(\x05R\vshapeStatus\x12\x1e\n" +
	"\n" +
	"revisionId\x18\x10 \x01(\tR\n" +
	"revisionId\x12\x1c\n" +
	"\tlineStyle\x18\x11 \x01(\tR\tlineStyle\x12&\n" +
	"\x0einfoRevisionId\x18\x12 \x01(\tR\x0einfoRevisionId\x12\x1c\n" +
	"\ttagIdList\x18\x13 \x01(\tR\ttagIdList\x12\x14\n" +
	"\x05extra\x18\x14 \x01(\tR\x05extra\x12\x1e\n" +
	"\n" +
	"linkIdList\x18\x15 \x01(\tR\n" +
	"linkIdList\x12\x1a\n" +
	"\brichText\x18\x16 \x01(\tR\brichText\x12\x1c\n" +
	"\tfillColor\x18\x17 \x01(\x05R\tfillColor\x12\x1c\n" +
	"\tpointList\x18\x18 \x01(\fR\tpointList\x12&\n" +
	"\x0econnectionBean\x18\x19 \x01(\tR\x0econnectionBean\x12 \n" +
	"\voptionsRepo\x18\x1a \x01(\tR\voptionsRepo\"B\n" +
	"\x12ShapeInfoProtoList\x12,\n" +
	"\x05proto\x18\x01 \x03(\v2\x16.booxpb.ShapeInfoProtoR\x05protoB6Z4github.com/sysop/ultrabridge/internal/booxnote/protob\x06proto3"

var (
	file_boox_proto_rawDescOnce sync.Once
	file_boox_proto_rawDescData []byte
)

func file_boox_proto_rawDescGZIP() []byte {
	file_boox_proto_rawDescOnce.Do(func() {
		file_boox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boox_proto_rawDesc), len(file_boox_proto_rawDesc)))
	})
	return file_boox_proto_rawDescData
}

var file_boox_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_boox_proto_goTypes = []any{
	(*NoteInfo)(nil),           // 0: booxpb.NoteInfo
	(*VirtualDoc)(nil),         // 1: booxpb.VirtualDoc
	(*VirtualPage)(nil),        // 2: booxpb.VirtualPage
	(*VirtualPageList)(nil),    // 3: booxpb.VirtualPageList
	(*NotePageModel)(nil),      // 4: booxpb.NotePageModel
	(*NotePageModelList)(nil),  // 5: booxpb.NotePageModelList
	(*ShapeInfoProto)(nil),     // 6: booxpb.ShapeInfoProto
	(*ShapeInfoProtoList)(nil), // 7: booxpb.ShapeInfoProtoList
}
var file_boox_proto_depIdxs = []int32{
	2, // 0: booxpb.VirtualPageList.proto:type_name -> booxpb.VirtualPage
	4, // 1: booxpb.NotePageModelList.proto:type_name -> booxpb.NotePageModel
	6, // 2: booxpb.ShapeInfoProtoList.proto:type_name -> booxpb.ShapeInfoProto
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_boox_proto_init() }
func file_boox_proto_init() {
	if File_boox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boox_proto_rawDesc), len(file_boox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_boox_proto_goTypes,
		DependencyIndexes: file_boox_proto_depIdxs,
		MessageInfos:      file_boox_proto_msgTypes,
	}.Build()
	File_boox_proto = out.File
	file_boox_proto_goTypes = nil
	file_boox_proto_depIdxs = nil
}
